steps:
  - name: 'hashicorp/terraform:1.0.0' 
    entrypoint: 'sh'
    args: 
    - '-c'
    - |
      cd Infra
      terraform init

  - name: 'hashicorp/terraform:1.0.0' 
    entrypoint: 'sh'
    args: 
    - '-c'
    - |
      cd Infra
      terraform plan
      
options:
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET

  
