steps:
  - name: Terraform Init
    args: ['terraform init']
    
  - name: Terraform Plan
    args: ['terraform plan -out=tfplan']

  - name: Terraform Apply
    if: github.ref == 'refs/heads/master' && github.event_name == 'push'
    run: terraform apply -auto-approve tfplan
